FROM ubuntu:22.04

# Install required system packages
RUN apt-get update && apt-get -y install \
    git htop vim python3 python3-pip sqlite3 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Copy and install Python dependencies
COPY requirements.txt ./requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# Working directory
WORKDIR /root/

# Environment variables
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Streamlit config
RUN mkdir -p /root/.streamlit && \
    bash -c 'echo -e "[general]\nemail = \"\"\n" > /root/.streamlit/credentials.toml' && \
    bash -c 'echo -e "[server]\nenableCORS = false\n" > /root/.streamlit/config.toml'

# Expose ports
# Streamlit
EXPOSE 8501
# Django (optional)
EXPOSE 8000

# Default command
CMD ["bash"]